### ISSUE TITLE
Problem in VMSizes-Must-Match-Template test when using Microsoft.Common.Section

### ISSUE THREAD

**Issue by ybbus** [Azure/arm-ttk#36]
Hi.

When the VMSize selector is inside a Microsoft.Common.Section, the script does not correctly retrieve the name of the step.
Instead, when it is retrieving the parent object name it will get the name of the section:
https://github.com/Azure/arm-ttk/blob/e2fbdcb93a4b2004c9ea953956b85248e0ef8c1c/arm-ttk/testcases/CreateUIDefinition/VMSizes-Must-Match-Template.test.ps1#L21

Later this name is used as the step name (even if it is the section name) and therefore the validation fails, even if it is correct:

https://github.com/Azure/arm-ttk/blob/e2fbdcb93a4b2004c9ea953956b85248e0ef8c1c/arm-ttk/testcases/CreateUIDefinition/VMSizes-Must-Match-Template.test.ps1#L23

**Comment by bmoore-msft** [comment]
@ybbus - I think this has been fixed (though recently) - can you try this scenario again?

**Comment by ybbus** [comment]
@bmoore-msft 
There was no code change in
arm-ttk/testcases/CreateUIDefinition/VMSizes-Must-Match-Template.test.ps1
since 18 days, and this change did not fix anything.

So unfortunately not.

**Comment by bmoore-msft** [comment]
thx - can you provide a CUID+template we can use for a repro?

**Comment by bmoore-msft** [comment]
Got it - thx...  

Another level of grouping that needs handling.

**Comment by ybbus** [comment]
Hi @bmoore-msft 

is there any chance to prioritize this?
We are blocked here since some weeks and are not able to publish our template on Azure Marketplace, because it gets rejected in the validation step by this issue.

**Comment by bmoore-msft** [comment]
@StartAutomating - I think we had a similar issue in another test, I suspect it may be prevalent in all CUIDs if we used the same pattern - can you grab this one?

@ybbus - if you are getting push back in Marketplace Certification, point them to this issue...  TTK results are still manually evaluated (iirc).

**Comment by ybbus** [comment]
@bmoore-msft Marketplace team did not respond for over 3 weeks now. Still stuck here... :(

**Comment by ybbus** [comment]
@bmoore-msft 
Something new on this one? This is still blocking our deployment to the Azure Marketplace.
Still no response from Marketplace Team.

**Comment by bmoore-msft** [comment]
Can you send me a link to the pull request that's being blocked?

**Comment by bmoore-msft** [comment]
email or here is fine

**Comment by ybbus** [comment]
Could you please contact me at: alexander.gehres@sap.com

Thanks

**Comment by bmoore-msft** [comment]
email sent - ping back here if you don't find it...

**Comment by zeeshaanali** [comment]
Any update on this? I am still seeing this issue in latest ttk tests.

**Comment by bmoore-msft** [comment]
This should be fixed - if you're still seeing it, please re-open and provide a sample we can repro with...
