### ISSUE TITLE
JSon Parsing, Nested Template

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#468]
When I embed the following resource

    {
      "name": "getManagementGroupName",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2019-10-01",
      "location": "[parameters('location')]",
      "properties": {
        "expressionEvaluationOptions": {
          "scope": "inner"
        },
        "mode": "Incremental",
        "template": {
          "$schema": "https://schema.management.azure.com/schemas/2019-08-01/managementGroupDeploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "resources": []
        }
      }
    },

Into a management group template, when running ARM TTK locally I get

  [-] Error occurred in test script '.\ARM\Policy\DiagnosticSettings\LogAnalytics\arm-ttk-tests.ps1' 250ms                                                                                  JsonReaderException: Additional text encountered after finished reading JSON content: :. Path '', line 1, position 10.                                                                  ArgumentException: Conversion from JSON failed with error: Additional text encountered after finished reading JSON content: :. Path '', line 1, position 10.                            at Expand-AzTemplate<Process>, C:\Users\drewk\Source Code\GitHub\drewkg\Azure\ARM-TTK\arm-ttk\Expand-AzTemplate.ps1: line 305                                                           at Test-AzTemplate<End>, C:\Users\drewk\Source Code\GitHub\drewkg\Azure\ARM-TTK\arm-ttk\Test-AzTemplate.ps1: line 626                                                                   at <ScriptBlock>, C:\Users\drewk\Source Code\GitHub\drewkg\Azure\ARM\Policy\DiagnosticSettings\LogAnalytics\arm-ttk-tests.ps1: line 1                                                   at <ScriptBlock>, C:\Users\drewk\OneDrive\Documents\PowerShell\Modules\Pester\4.1.0\Pester.psm1: line 825                                                                               at Invoke-Pester<End>, C:\Users\drewk\OneDrive\Documents\PowerShell\Modules\Pester\4.1.0\Pester.psm1: line 840                                                                          at <ScriptBlock>, C:\Users\drewk\Source Code\GitHub\drewkg\Azure\Utilities\Run-ARMTTK.ps1: line 9                                                                                       at <ScriptBlock>, C:\Users\drewk\Source Code\GitHub\drewkg\Azure\Utilities\Run-ARMTTK.ps1: line 8                                                                                       at <ScriptBlock>, <No file>: line 1  

The complete template can be found at https://raw.githubusercontent.com/drewkg/Azure/feature/ARMTTK/ARM/Policy/DiagnosticSettings/LogAnalytics/azuredeploy.json

**Comment by bmoore-msft** [comment]
@drewkg - can you try this with the latest bits, I think this may have been fixed.

**Comment by drewkg** [comment]
@bmoore-msft - just tried this and still getting the same issue.

**Comment by drewkg** [comment]
Interestingly if I change the scope to outer it parses correctly, and for my requirements I think that is actually fine.

**Comment by drewkg** [comment]
Been digging into the PS, it appears that something is not quite right within Resolve-JSONContent, as the $foundInnerTemplate is not an object when returned after parsing this template.

The result is the inner template substitution ends up producing a template text of 

"template": {}{   "$schema": "https://schema.management.azure.com/schemas/2019-08-01/managementGroupDeploymentTemplate.json#", ...

notice the template":{}{ at the start of the file, which of course is invalid json as per the error message.

**Comment by bmoore-msft** [comment]
Got it - thanks... it looks like the recent change may have caused this (rather than fixed :p)

**Comment by drewkg** [comment]
Updated path to failing sample - https://raw.githubusercontent.com/drewkg/Azure/main/ARM/Policy/DiagnosticSettings/LogAnalytics/azuredeploy.json

**Comment by StartAutomating** [comment]
Digging into this one a bit it appears Resolve-JSONContent is failing to find the text position of the match, which causes the template extraction to fail.  

This scenario (failure to find) should be handled more gracefully.

In this particular case, the failure to find is due to the regular expression failing to locate the main resources section.  I am investigating why that is / how to ensure those items match as well.

**Comment by StartAutomating** [comment]
We have a fix ready and are adding tests to avoid regressions.
